---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.4
  - name: debian-8.0
  - name: centos-6.6

suites:
- name: package
  run_list:
    - recipe[freeswitch]
  attributes:
    freeswitch:
      local_ip: '0.0.0.0'
      domain: 'foo.bar.com'
- name: source
  run_list:
    - recipe[freeswitch]
  attributes:
    freeswitch:
      install_method: 'source'
      local_ip: '0.0.0.0'
      domain: 'foo.bar.com'
- name: lwrp
  run_list:
    - recipe[freeswitch]
    - recipe[freeswitch-test::lwrp]
  attributes:
    freeswitch:
      local_ip: '0.0.0.0'
      domain: 'foo.bar.com'
