---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: tdb-ubuntu
  driver_config:
    box: tdb-ubuntu1204-v9
    box_url: http://ci.mojolingo.com/job/Telephony-Dev-Box-Base-Boxen/9/artifact/tdb-ubuntu1204.box
    customize:
      memory: 1024
- name: debian
  driver_config:
    box: debian
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.1.0_provisionerless.box
    customize:
      memory: 1024

suites:
- name: package
  run_list: ['recipe[freeswitch]']
  attributes: {
    freeswitch: {
      local_ip: '0.0.0.0',
      domain: 'foo.bar.com'
    }
  }
- name: source
  run_list: ['recipe[freeswitch]']
  attributes: {
    freeswitch: {
      install_method: 'source',
      local_ip: '0.0.0.0',
      domain: 'foo.bar.com'
    }
  }
- name: rayo
  run_list: ['recipe[freeswitch::rayo]']
  attributes: {
    freeswitch: {
      local_ip: '0.0.0.0',
      domain: 'foo.bar.com'
    }
  }
