default['freeswitch']['source']['git_uri'] = "git://git.freeswitch.org/freeswitch.git"
default['freeswitch']['source']['git_branch'] = "v1.2.stable"
default['freeswitch']['source']['enabled'] = "true"
default['freeswitch']['source']['binpath'] = "/usr/local/freeswitch/bin"
default['freeswitch']['source']['confpath'] = "/usr/local/freeswitch/conf"
default['freeswitch']['source']['homedir'] = "/usr/local/freeswitch"
